### ISSUE TITLE
Timm library version problem

### ISSUE THREAD

**Issue by mertyyanik** [selimsef/dfdc_deepfake_challenge#11]
Timm library updated version causes trouble in the code.
https://github.com/selimsef/dfdc_deepfake_challenge/blob/9925d95bc5d6545f462cbfb6e9f37c69fa07fde3/Dockerfile#L59

Installing an older version resolved the issue.
`pip install timm==0.1.26`

**Comment by Allen-Hu** [comment]
@mertyyanik Thanks for sharing this, however I'm getting another error while using the `predict_submuission.sh` script:

```
ImportError: cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.7/site-packages/torch/_six.py)
```

I suppose this is due to a PyTorch update? Would you share the PyTorch version you're using during this competition?
Thanks in advance!

**Comment by AyeshaMalikAyesha** [comment]
@enquestor I got the same torch._six error How do I resolve this can you please help me? I have used the timm version 0.1.26 so which pytorch version should I use to get rid of this error
