### ISSUE TITLE
could i download pretrained model about dfdc dataset?  Now I get an error.

### ISSUE THREAD

**Issue by kwonjunn01** [selimsef/dfdc_deepfake_challenge#14]
--2020-11-02 14:27:42--  https://github.com/selimsef/dfdc_deepfake_challenge/releases/download//final_999_DeepFakeClassifier_tf_efficientnet_b7_ns_0_23
Resolving github.com (github.com)... 15.164.81.167
Connecting to github.com (github.com)|15.164.81.167|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-02 14:27:42 ERROR 404: Not Found.

i encontered this issue. What can be done to solve this problem.

**Comment by selimsef** [comment]
You  can download them from the releases page https://github.com/selimsef/dfdc_deepfake_challenge/releases
