### ISSUE TITLE
Unable to understand extraction of crops

### ISSUE THREAD

**Issue by deepaks2112** [selimsef/dfdc_deepfake_challenge#16]
https://github.com/selimsef/dfdc_deepfake_challenge/blob/9925d95bc5d6545f462cbfb6e9f37c69fa07fde3/preprocessing/extract_crops.py#L42

Why are you multiplying the coordinates of bounding box by 2? It will shift the region that we want to crop. I think it should not be multiplied.

Thanks.

**Comment by selimsef** [comment]
@deepaks2112 Actually everything is spot on, but it is not obvious.
Would be better to have it as a parameter, but at the time I did not think it would be used by others :) 
I used downscaled images for face detection - see https://github.com/selimsef/dfdc_deepfake_challenge/blob/ef703c2745bd0615fef6e03c2a519cd59273f9ff/preprocessing/face_detector.py#L67
Therefore to extract crops coordinates should be multiplied by scale factor first.

**Comment by deepaks2112** [comment]
Yes, I missed that part. It is clear to me now. Thanks for the response.
