### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by guyreading** [selimsef/dfdc_deepfake_challenge#18]
Is there a way of using the trained weights & do inference using CPU only? My GPU can't handle inference with the current settings...

**Comment by guyreading** [comment]
Solved: used `with torch.cuda.amp.autocast():` in kernel_utils, line 334, for the subsquent 3 lines. & then changed all pointers to cuda with "cpu", removed the .half()'s where they were as incompatible with cpu use.

**Comment by epiqueras** [comment]
@guyreading @selimsef `torch.cuda.amp.autocast()` is not available in `PYTORCH="1.4"` which the Docker image is built for.

Is there a workaround you would recommend?

**Comment by selimsef** [comment]
There is no need to use `amp` for inference on CPU. You can just change half -> float  inputs and device to "cpu" as @guyreading did.

**Comment by epiqueras** [comment]
@selimsef yeah, I ended up figuring that out reading the docs.

Thanks for confirming!

This doesn't do too well on side shots, does it? I tested it, and it gave me ~0.3 for an obviously fake video.

**Comment by selimsef** [comment]
@epiqueras Yes, multiple reasons for that:
- less training data for that view
- In the training set there were two actors per video with side shots, one of them was not fake. So it created a lot of noise in training. 
- MTCNN might miss faces on side shots or bounding boxes won't be accurate

**Comment by epiqueras** [comment]
@selimsef interesting; thanks for the info.

I tested it on frontal webcam shots, and it works almost perfectly.

What are your thoughts on using MTCNN vs. using some sort of reversal/adaptation of the feedback loops the networks that generate deepfakes use? I assume that would only work for targeting specific algorithms and using approaches like yours can work against a broader range of techniques?
