### ISSUE TITLE
Resize the videos

### ISSUE THREAD

**Issue by hongshuochen** [selimsef/dfdc_deepfake_challenge#21]
Hi,

I just have a quick question. You mention that you resize the videos before the face detector.
Do we need to resize the videos before we run preprocess_data.sh?
Or preprocess_data.sh would also handle the resize of the videos as well when we run face detector?

I can not find the code you resize the image. This is the closest thing I find in your code.
https://github.com/selimsef/dfdc_deepfake_challenge/blob/ef703c2745bd0615fef6e03c2a519cd59273f9ff/preprocessing/face_detector.py#L67

Thank you!

**Comment by selimsef** [comment]
Hi,
I did that in kernel during inference. See https://github.com/selimsef/dfdc_deepfake_challenge/blob/ef703c2745bd0615fef6e03c2a519cd59273f9ff/kernel_utils.py#L227
