### ISSUE TITLE
Why RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED?

### ISSUE THREAD

**Issue by sifan-sifan** [selimsef/dfdc_deepfake_challenge#22]
when i run train_classifier.py,i meet the problem.
![image](https://user-images.githubusercontent.com/51920228/111440081-f6034c00-8740-11eb-939a-77a41805b5ee.png)

I've been stuck here for two days.
could you explain it in detail? thank you!

**Comment by selimsef** [comment]
If you run the code locally you need 
- nvidia drivers installed
- cuda
- pytorch for the same cuda version 
It seems like you have wrong setup

**Comment by cruisewu** [comment]
I used Win11 WSL2+Docker. Have the same problem "CUDNN_STATUS_NOT_INITIALIZED". 
![image](https://user-images.githubusercontent.com/16588779/162859584-4391c2bd-1ce1-4926-aefc-d12d3cb862a1.png)
Is something wrong with that?
