### ISSUE TITLE
submission.csv all predictions are below 0.5

### ISSUE THREAD

**Issue by mylastfight** [selimsef/dfdc_deepfake_challenge#25]
Hi Selim, 

Thank you for sharing your great work here, tried to use your predict_submission.sh to reproduce the submission.csv by using 7 efficientnet-b7 models on test_videos folder, but the prediction scores for all 400 videos are smaller than 0.5, most of them around 0.3-0.4, guess I did something wrong here, but just cannot figure out what could be the possible reasons, can help here?

Xu

**Comment by mylastfight** [comment]
./dataset/debug_videos/aagfhgtpmv.mp4 (it is a fake video)
predicted bpred values: 
[0.4526 0.4292 0.4878 0.4688 0.4766 0.499  0.4365 0.4514 0.4163 0.4373
 0.4688 0.4187 0.4468 0.376  0.4214 0.4277 0.4077 0.4048 0.3591 0.4617
 0.3335 0.4595 0.4336 0.321  0.3293 0.3787 0.4197 0.3926 0.362  0.4355
 0.3987 0.4265 0.435  0.4116]
./dataset/debug_videos/aayfryxljh.mp4 (should be a real video)
predicted bpred values:
 [0.4412 0.462  0.4646 0.4517 0.4302 0.4626 0.4443 0.4163 0.4387 0.3057
 0.3477 0.487  0.4778 0.4846 0.4941 0.473  0.4773 0.4724 0.4797 0.4612
 0.4573 0.4827 0.4797 0.453  0.445  0.4626 0.4478 0.3813 0.3896 0.452
 0.4045 0.4841]

**Comment by Allen-Hu** [comment]
I also got this using pretrained weights. You can try retraining the whole thing and it should be fine.

**Comment by selimsef** [comment]
seems to be fixed by #27

**Comment by AyeshaMalikAyesha** [comment]
@selimsef I installed the timm version 0.1.18 but I got error torch._six but when I use higher version, the pretrained model always predict 0.5. Could you please help me what should I do? Could you please specify the pytorch version

**Comment by AyeshaMalikAyesha** [comment]
> I also got this using pretrained weights. You can try retraining the whole thing and it should be fine.

Can we retrained the model on google colab using free GPU resource

**Comment by AyeshaMalikAyesha** [comment]
I resolved the issue by chnaging the np.int to np.int64 in kernel_utils.py file line no. 53
