### ISSUE TITLE
MTCNN thresholds

### ISSUE THREAD

**Issue by miaoct** [selimsef/dfdc_deepfake_challenge#5]
In face_detector.py :
 self.detector = MTCNN(margin=0,thresholds=[0.85, 0.95, 0.95], device=device)

but in kernel_utils.py :
self.detector = MTCNN(margin=0, thresholds=[0.7, 0.8, 0.8], device="cuda")

this is why ?

thank you

**Comment by selimsef** [comment]
The goal of high thresholds in the preprocessing code is to reduce the number of false positive face predictions (which would add noise) in train data. 

For  inference due to different video quality in the public test set I reduced these thresholds.

**Comment by miaoct** [comment]
ok, I also find this 👍 
def confident_strategy(pred, t=0.87):
   pred = np.array(pred)
   size = len(pred)
   fakes = np.count_nonzero(pred > t)
   if fakes > size // 3 and fakes > 11:
       return np.mean(pred[pred > t])
   elif np.count_nonzero(pred < 0.2) > 0.6 * size:
       return np.mean(pred[pred < 0.2])
   else:
       return np.mean(pred)

and 
def confident_strategy(pred, t=0.8):
    pred = np.array(pred)
    sz = len(pred)
    fakes = np.count_nonzero(pred > t)
    # 11 frames are detected as fakes with high probability
    if fakes > sz // 2.5 and fakes > 11:
        return np.mean(pred[pred > t])
    elif np.count_nonzero(pred < 0.2) > 0.9 * sz:
        return np.mean(pred[pred < 0.2])
    else:
        return np.mean(pred)

so, this question as same as MTCNN thesholds 

thank you very much!

**Comment by selimsef** [comment]
the first one was best on public LB, second one is more conservative and was used in winning private submission.
