### ISSUE TITLE
No module named 'VideoDataset'

### ISSUE THREAD

**Issue by maymay1982** [selimsef/dfdc_deepfake_challenge#7]
When I ran `python preprocessing/detect_original_faces.py --root-dir DATA_ROOT`, I encountered an error:
Traceback (most recent call last):
  File "preprocessing/detect_original_faces.py", line 14, in <module>
    import face_detector, VideoDataset
ModuleNotFoundError: No module named 'VideoDataset'
How can I solve this problem?

**Comment by selimsef** [comment]
that's because you don't include current path to python and python interpreter doesn't see these modules, jus add `PYTHONPATH=. python ...` and it will fix the problem
