### ISSUE TITLE
Will you publish a paper soon

### ISSUE THREAD

**Issue by niyunsheng** [selimsef/dfdc_deepfake_challenge#8]
looking forward to that

**Comment by selimsef** [comment]
That's an interesting question, the private dataset is not fully released (only synthetic part is available) and therefore it would be hard to make ablation studies without organic videos.

**Comment by niyunsheng** [comment]
thanks for your answer

**Comment by AyeshaMalikAyesha** [comment]
@selimsef have you published the paper?
